### ISSUE TITLE
allow a customized list of commands to skip

### ISSUE THREAD

**Issue by AaronLasseigne** [fisherman/done#11]
I see that it has an internal list of commands to skip but it would be great if we could add to the list.

**Comment by aristidesfl** [comment]
@AaronLasseigne which operative system are you using?

**Comment by AaronLasseigne** [comment]
I'm in iTerm2 on OSX 10.12.3. 915cb64 doesn't resolve the issue for me. If I open vim, wait more than 10 seconds, and then close it I get a notification. Originally I had requested this because I've added a custom command to launch my editor (neovim) with certain options. I was wanting to ignore my custom command.

**Comment by aristidesfl** [comment]
The plugin is broken now and is not event supposed to send any notifications. I will let you know when its fixed so you can test it again. Thank you for your feedback.

**Comment by aristidesfl** [comment]
@AaronLasseigne can you please test v1.0.0? It should be fixed. Make sure you have fish >2.3.0 installed. Thanks!

**Comment by AaronLasseigne** [comment]
I'm still having some issues but I've corrected them with #13.

**Comment by aristidesfl** [comment]
Merged, thanks!
