### ISSUE TITLE
Specify whether the command finished successfully.

### ISSUE THREAD

**Issue by skorokithakis** [fisherman/done#16]
Perhaps the notification can say whether the command finished with an error or successfully? This could be as simple as "Finished in X" and "Errored in X".

**Comment by aristidesfl** [comment]
Good idea. Probably not "Errored' though.

> "To use "errored" you would have to consider error a verb, but the dictionary doesn't. "Error" is a noun, used to mean mistake. You wouldn't say "The program mistaked at line 44." Your usage "threw an error" is correct, because it uses error as a noun."

**Comment by skorokithakis** [comment]
Yeah, I realized that as I was typing it, but all the alternatives felt worse. "Finished in X" "Finished with an error in X" is too long for the failure case, but maybe adding an extra line with "There was an error" at the end is good enough?

**Comment by aristidesfl** [comment]
`Finished in X with errors` doesn't seem that long: 

![screen shot 2017-02-12 at 18 19 02](https://cloud.githubusercontent.com/assets/208149/22864335/c379e81a-f14f-11e6-96c7-925dd9de2e98.png)


Other options would be `Failed in X`:
![screen shot 2017-02-12 at 18 20 10](https://cloud.githubusercontent.com/assets/208149/22864343/0628755a-f150-11e6-9d13-0c50e92e5577.png)

**Comment by jbucaran** [comment]
First one sounds more natural.

**Comment by skorokithakis** [comment]
Agreed, that seems fine to me too.

**Comment by aristidesfl** [comment]
What do you guys think about `Finished in 2m 32s` vs `Done in 2m 32s` ?

![screen shot 2017-02-12 at 18 50 52](https://cloud.githubusercontent.com/assets/208149/22864574/3e11b716-f154-11e6-9e35-77a72245ce3e.png)

First seems more natural but second is shorter and playful?

**Comment by jbucaran** [comment]
Definitely `done`.

**Comment by aristidesfl** [comment]
And for errors?

![screen shot 2017-02-12 at 18 59 23](https://cloud.githubusercontent.com/assets/208149/22864636/9a73adce-f155-11e6-810d-4e99bae213b0.png)

😄

**Comment by aristidesfl** [comment]
I wonder if `Overdone after 2m 32s` is clear enough or if `Burned after 2m 32s` would be better.
Also we could add the exit code in case of error `Overdone (1) after 2m 32s`

**Comment by skorokithakis** [comment]
I think that's getting a bit too cryptic (not to mention that the metaphor doesn't work because the command took *less* time than it should :P).

**Comment by aristidesfl** [comment]
hihi, so what, keep it to `Done in X with errors`?

**Comment by skorokithakis** [comment]
Sounds good to me, or "Finished with errors in X".

**Comment by aristidesfl** [comment]
For errors ended up with something like `Exit status 1 after 3m 23s`.

Done in https://github.com/fisherman/done/releases/tag/1.2.0
