### ISSUE TITLE
'xprop:  unable to open display ''' message spam, when no display is available

### ISSUE THREAD

**Issue by mokasin** [fisherman/done#20]
When logging in remotely over SSH in a non-graphical session, after every command

```
xprop:  unable to open display ''
```

is displayed. Maybe check for `DISPLAY` environment variable first, before running [`xprop`](https://github.com/fisherman/done/blob/master/conf.d/done.fish#L32)?

So in the spirit of
```
[ -n "$DISPLAY" ]; and xprop etc
```

**Comment by aristidesfl** [comment]
So you installed this plugin in a server because of your dotfiles?

**Comment by mokasin** [comment]
It's not on server but in a machine I also work on remotely.

Am 9. Mai 2017 22:22:13 MESZ schrieb "Francisco Lourenço" <notifications@github.com>:

**Comment by aristidesfl** [comment]
I guess we should disable Done completely if the login is from ssh..

**Comment by mokasin** [comment]
Yes, that's reasonable

**Comment by dpc** [comment]
I was going to report the same problem.

Maybe you could try to fall back to use `tmux display`?

Also, as an immediate fix, please just pipe errors to `/dev/null` and release it. I really like this plugin, but this `xprop` thing is really annoying. :)

**Comment by aristidesfl** [comment]
I will try address this tonight.
@dpc In the meanwhile you can actually fork it and install from your repo with fisherman.

**Comment by aristidesfl** [comment]
@dcp with `tmux display` do you mean that you would like to have a notification in tmux status bar when you are using tmux over ssh?

**Comment by aristidesfl** [comment]
Can you please test if https://github.com/fisherman/done/tree/20 fixes the problem?

```bash
fisher uninstall done
fisher install fisherman/done:20
```

**Comment by dpc** [comment]
```
[I] dpc@futex ~> ls
''$'\266\177'   
(... actual output ...)
```

**Comment by aristidesfl** [comment]
fish version?

**Comment by dpc** [comment]
```
fish, version 2.5.0
```

**Comment by aristidesfl** [comment]
@dpc just updated with a new version, can you please try again? If you still have the same branch installed `fisher update` should be enough, otherwise restart fish after that.

**Comment by mokasin** [comment]
I can confirm, that the latest update does not produce the unwanted `xprop` in an `ssh` session.

**Comment by c02y** [comment]
When I'm in tty mode such as "Ctrl-Alt-F2", a line 

    xprop: unable to open display''

will always be displayed before fish prompt.

I tried to update done.fish to the latest version (commit 1485d72), but it is still the same result. It is normal when I'm in Desktop.

**Comment by aristidesfl** [comment]
@c02y thanks for the report! can you test [1.4.1](https://github.com/fisherman/done/releases/tag/1.4.1)?

**Comment by c02y** [comment]
OK, it works fine. But the line containing "$SSH_CLIENT" is unnecessary, already tested earlier.

Or you can just replace the part in done.fish with the snippet I posted earlier.

**Comment by aristidesfl** [comment]
@c02y I left it because I didn't have opportunity to test what happens when you ssh into a mac. Next time you feel like contributing actual code feel free to open a pull request :)

**Comment by c02y** [comment]
I don't have a mac, so I cannot help with that, but I tested between Linux boxes.

It is not complicated modification, so for me it's unnecessary to open a pull request, hope you wouldn't mind.
