### ISSUE TITLE
"Unknown option --app-name=terminal"

### ISSUE THREAD

**Issue by c02y** [fisherman/done#22]
It doesn't work for my old platform which is CentOS 6.5 32-bit

notify-send -v: 0.5.0

Error message:

    Unknown option --app-name=terminal

Don't know if it is caused by the old version of notify-send, but I cannot get new version right now.

So, after modifying the line in done.fish

    notify-send --icon=terminal --app-name=terminal "$title" "$message"

to

    notify-send --icon=terminal "$title" "$message"

it will work.

BTW:  you didn't mention in the README.md file that the `done` plugin depends on [humanize_duration](https://github.com/fisherman/humanize_duration) plugin.

**Comment by aristidesfl** [comment]
Dependencies should be installed automatically. Is it still important to know the dependencies if they are handled automatically?

**Comment by c02y** [comment]
Since you got "Manually:" line in it, manually installing `done` plugin won't make it work as expected since no dependencies will be installed, I guess it's better to mention the dependencies.

**Comment by aristidesfl** [comment]
Good point.. did you install it manually?

**Comment by aristidesfl** [comment]
Can't find documentation about `--app-name`.
notify-send fixed in https://github.com/fisherman/done/releases/tag/1.2.4

**Comment by c02y** [comment]
Yes, I installed it manually, I don't use fisher or any other kind of plugin manager of fish-shell.

**Comment by aristidesfl** [comment]
humanize_duration doesn't have manual install instructions. how did you install it?

**Comment by jbucaran** [comment]
I guess @c02y just put the file inside their functions directory?

**Comment by c02y** [comment]
Yes, just put the done.fish and humanize_duration.fish in ~/.config/fish/functions directory.
