### ISSUE TITLE
Make the list of excluded commands configurable

### ISSUE THREAD

**Issue by slapresta** [fisherman/done#6]
It would be nice if I could exclude certain commands from the list; particularly those who are interactive, such as `vim`, `git commit` or `git add -i`. Since I'm interacting with those commands myself, I get no value from being notified about those commands finishing; and since the whole command is driven by human actions, they often take more than ten seconds.

I see in the source code that there's already a list of commands to ignore; it would be nice if it were customizable. If you have any ideas about how this should be implemented, I may be able to implement this myself.

Another approach would be to detect if a command is interactive, I guess? I have no idea if that's remotely feasible or not.

**Comment by aristidesfl** [comment]
@slapresta thanks for the suggestion. Interactive commands are only supposed to terminate when you are interacting with them and thus the notification should not be shown, except at the moment only iTerm is supported. What terminal emulator are you using?

**Comment by aristidesfl** [comment]
@slapresta are you using linux?

**Comment by slapresta** [comment]
Sorry, I forgot to reply; I'm using Terminal.app on OSX. I notice now that only iTerm is supported :) Thanks!

**Comment by aristidesfl** [comment]
All terminals are supported in v0.4.0 on macOS, so I don't even see a need to have a list of excluded apps on macOS. Please update with `fisher update`, and report if not working correctly. Closing for now.
